CREATE USER APP IDENTIFIED BY APP;
GRANT CREATE session TO APP;
GRANT CONNECT, RESOURCE TO APP;
ALTER USER APP QUOTA UNLIMITED ON USERS;

CREATE TABLE APP.DEVELOPERS (
    ID              NUMBER(5)     NOT NULL,
    USERNAME        VARCHAR2(25)  NOT NULL,
    GITHUB          VARCHAR2(120) NOT NULL,
    BIRTH_YEAR      NUMBER(4)     NOT NULL,
    DT_REGISTRATION DATE DEFAULT SYSDATE
);

INSERT INTO APP.DEVELOPERS (ID, USERNAME, GITHUB, BIRTH_YEAR) VALUES (1, 'avcaliani', 'https://github.com/avcaliani', 1997);
